all:
	python fill_parameters.py parameters-sorted.txt > ui/ensemble_parameters_basic.ui
	python fill_parameters.py parameters-system.txt > ui/ensemble_parameters_system.ui
	python fill_parameters.py parameters-all.txt > ui/ensemble_parameters_all.ui
	python fill_parameters.py parameters-task.txt > ui/ensemble_parameters_task.ui
	python fill_parameters.py parameters-advanced.txt > ui/ensemble_parameters_advanced.ui
	python fill_parameters.py parameters-wirescanner.txt > ui/ensemble_parameters_wirescanner.ui
